baseURL = "https://jmsdnns.com/"
locale = "en-us"
title = "JmsDnns"

disableKinds = ["sitemap"]

[taxonomies]
# disabled - using sections for series instead
# series = "series"
[outputs]
section = ['html', 'rss']

[pagination]
pagerSize = 5

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = false
[markup.highlight]
codeFences = true
noClasses = false
